# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-03 15:52
from __future__ import unicode_literals

from django.db import migrations, models
import item.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to=item.utils.PathAndRename('file', 'image', 'test'))),
                ('size', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
